This is makeindex, version 2.15 [TeX Live 2014] (kpathsea + Thai support).
Scanning style file /Users/ska/Documents/thesis/.texpadtmp/main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/ska/Documents/thesis/.texpadtmp/main.acn....done (14 entries accepted, 0 rejected).
Sorting entries....done (74 comparisons).
Generating output file /Users/ska/Documents/thesis/.texpadtmp/main.acr....done (30 lines written, 0 warnings).
Output written in /Users/ska/Documents/thesis/.texpadtmp/main.acr.
Transcript written in /Users/ska/Documents/thesis/.texpadtmp/main.alg.
